=== megahelio/HybridServer/HybridServer/examplexsd.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="recetas" type="recetasType" />
    <xs:complexType name="recetasType">
        <xs:sequence>
            <xs:element name="receta" type="recetaType" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="recetaType">
        <xs:sequence>
            <xs:element name="titulo" type="xs:string" />
            <xs:element name="id" type="xs:string" />
            <xs:element name="comensales" type="xs:positiveInteger" />
            <xs:element name="dificultad" type="dificultadType" default="Medio" />
            <xs:element name="ingredientes" type="ingredientesType" />
            <xs:element name="pasos" type="pasosType" />
            <xs:element name="autores" type="autoresType" minOccurs="0" />
            <xs:element name="descripcion" type="xs:string" minOccurs="0" />
            <xs:element name="tiempo" type="xs:nonNegativeInteger" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="dificultadType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Bajo" />
            <xs:enumeration value="Medio" />
            <xs:enumeration value="Alto" />
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="ingredientesType">
        <xs:sequence>
            <xs:element name="ingrediente" type="ingredienteType" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="ingredienteType">
        <xs:sequence>
            <xs:element name="nombre" type="xs:string" />
            <xs:element name="medida" type="medidaType" default="gramo" />
            <xs:element name="cantidad" type="xs:decimal" />
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="medidaType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="miligramo" />
            <xs:enumeration value="gramo" />
            <xs:enumeration value="kilogramo" />
            <xs:enumeration value="mililitro" />
            <xs:enumeration value="litro" />
            <xs:enumeration value="pizca" />
            <xs:enumeration value="cucharilla" />
            <xs:enumeration value="cuchara" />
            <xs:enumeration value="unidades" />
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="pasosType">
        <xs:sequence>
            <xs:element name="paso" type="pasoType" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="pasoType">
        <xs:sequence>
            <xs:element name="orden" type="xs:positiveInteger" />
            <xs:element name="descripcion" type="xs:string" />
            <xs:element name="detalle" type="xs:string" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="autoresType">
        <xs:sequence>
            <xs:element name="autor" type="xs:string" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== megahelio/HybridServer/HybridServer/exampleReceta.xml
<?xml version="1.0"?>
<recetas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="examplexsd.xsd">
    <receta>
        <titulo>Título de la receta</titulo>
        <id>identificador único</id>
        <comensales>2</comensales>
        <dificultad>Medio</dificultad>
        <ingredientes>
            <ingrediente>
                <nombre>nombre del ingrediente</nombre>
                <medida>litro</medida>
                <cantidad>3</cantidad>
            </ingrediente>
            <!-- más ingredientes -->
        </ingredientes>
        <pasos>
            <paso>
                <orden>1</orden>
                <descripcion>breve descripción</descripcion>
                <detalle>texto adicional</detalle>
            </paso>
            <paso>
                <orden>2</orden>
                <descripcion>breve descripción</descripcion>
                <detalle>texto adicional</detalle>
            </paso>
            <!-- más pasos -->
        </pasos>
        <autores>
            <autor>identificador único del autor</autor>
            <!-- más autores -->
        </autores>
        <descripcion>descripción de la receta</descripcion>
        <!-- tiempo de preparación en minutos -->
        <tiempo>
            120</tiempo>
    </receta>
    <!-- más recetas -->
</recetas>
